apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    isDefault: true
    uid: cassandra-ds
    url: "172.28.0.5:9042"
    jsonData:
      keyspace: taasim
      consistency: ONE
